# arm_controller:
#   type: effort_controllers/JointTrajectoryController
#   joints:
#     - base_link__link1
#     - link1__link2
#     - link2__link3
#     - link3__link4
#     - link4__link5
#     - gripper_joint
#   gains:
#     base_link__link1:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     link1__link2:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     link2__link3:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     link3__link4:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     link4__link5:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     gripper_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
# hand_controller:
#   type: effort_controllers/JointTrajectoryController
#   joints:
#     - gripper_right_joint
#   gains:
#     gripper_right_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

controller_list:
  - name: /cobot/arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - base_link__link1
      - link1__link2
      - link2__link3
      - link3__link4
      - link4__link5
      - gripper_joint

  - name: /cobot/gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - gripper_right_joint
      - gripper_left_joint

